name: Deploy to TestFlight

jobs:
  build:
    name: iOS Production Build
    type: build
    params:
      platform: ios
      profile: production

  submit:
    name: Submit to TestFlight
    type: submit
    needs:
      - build
    params:
      platform: ios
      profile: production
      build_id: ${{ needs.build.outputs.build_id }}
